#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="rootCase"
loseCases="0.1 0.2 0.3 1.1 1.3 1.5 1.7*"

for caseName in $keepCases
do
(
    cd $caseName || exit
    foamCleanTutorials
)
done

for caseName in $loseCases
do
    removeCase $caseName
done

#------------------------------------------------------------------------------
